---
title: "Philly Quizzo!"
subtitle: "A Tour Through Philadelphia's Vibrant Quizzo Scene"
---

## Welcome!

### Group Members 

Brooke Acosta, Michael Dunst, Sofia Fasullo

### Research Question

Which Quizzo locations are closest to the user based on location and day of week selected.

## The Approach

We will be creating a dataset that includes Quizzo locations in Philadelphia, night of week that Quizzo is available at each location, and neighborhood.  We will use this data to create an interactive dashboard that the public can filter through and use to find Quizzo locations nearest to them on their desired date. We will use the following approach: 

### Methods

•	Web scrape using Foursquare Places API to find Quizzo locations and date of Quizzo nights in Philadelphia.
•	Use OMNX to map routes to Quizzo locations.
•	Calculate the distance between the user and Quizzo locations and allow the user to find the five Quizzo locations closest to them. 
•	Create an interactive dashboard for users to select their preferred Quizzo night and the dashboard will filter the dataset based on location/proximity to Quizzo bar and date of week selected. 

:::

## Find out more

The code for this repository is hosted on our course's GitHub page: [https://github.com/MUSA-550-Fall-2023/quarto-website-template](https://github.com/MUSA-550-Fall-2023/quarto-website-template).

We covered the basics of getting started with Quarto and GitHub Pages in week 9. Take a look at
[the slides for lecture 9A](https://musa-550-fall-2023.github.io/content/week-9/lecture-9A.html) to find out more.






 
