---
title: "Philly Quizzo!"
subtitle: "A Tour Through Philadelphia's Vibrant Quizzo Scene"
---

## Welcome! 

Group Members: Brooke Acosta, Michael Dunst, Sofia Fasullo

### Research Question

Which Quizzo locations are closest to the user based on location and day of week selected. 

## The Approach

We will be creating a dataset that includes Quizzo locations in Philadelphia, night of week that Quizzo is available at each location, and neighborhood.  We will use this data to create an interactive dashboard that the public can filter through and use to find Quizzo locations nearest to them on their desired date. 

### Methods

- Data is collected through a means more sophisticated than downloading (e.g. scraping, API). 

- The analysis of the data is reasonably complex, involving multiple steps (geospatial joins/operations, data shaping, data frame operations, etc). 

- The analysis of the data is reasonably complex, involving multiple steps (geospatial joins/operations, data shaping, data frame operations, etc). 

- The project includes a deployed Panel dashboard.